// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-jieql2xroD7yexbOvvodjsyY17-qZYY',
    appId: '1:671797807426:web:858490a07a1795e4ad60db',
    messagingSenderId: '671797807426',
    projectId: 'testntrack-62626',
    authDomain: 'testntrack-62626.firebaseapp.com',
    storageBucket: 'testntrack-62626.appspot.com',
    measurementId: 'G-V6919XVRVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATacLLsv3cradLINUly2bJg-86swqwo8k',
    appId: '1:671797807426:android:f5efc8b94077b0aead60db',
    messagingSenderId: '671797807426',
    projectId: 'testntrack-62626',
    storageBucket: 'testntrack-62626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq5zbOpBAkeT6dGdNqEzQlJVmd7p0M-qM',
    appId: '1:671797807426:ios:39071dd418b12880ad60db',
    messagingSenderId: '671797807426',
    projectId: 'testntrack-62626',
    storageBucket: 'testntrack-62626.appspot.com',
    iosClientId: '671797807426-se0emcg2nclailo8fdcpqng399gffnpb.apps.googleusercontent.com',
    iosBundleId: 'com.testntrack.app',
  );
}
